/*CONECTADO A SQL PLUS*/

CONNECT / AS SYSDBA

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- CREACIÃ“N DEL USUARIO
CREATE USER C##eataway IDENTIFIED BY sws2024;

-- ASIGNACIÃ“N DE PRIVILEGIOS AL USUARIO
GRANT CONNECT TO C##eataway;

GRANT ALL PRIVILEGES TO C##eataway;

-----------------------------------------------
--CREACION DE LAS TABLAS--
-------------------------------------------------

-- Tabla CategorÃ­a
CREATE TABLE Categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL
);

-- Tabla Usuarios
CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    primer_apellido VARCHAR2(50) NOT NULL,
    segundo_apellido VARCHAR2(50),
    correo VARCHAR2(100) NOT NULL UNIQUE,
    password varchar(200) NOT NULL,
    foto VARCHAR2(1024)
);
ALTER TABLE Usuarios
MODIFY foto VARCHAR2(1024);

-- Tabla Locales
CREATE TABLE Locales (
    id_local NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    id_categoria NUMBER,  -- RelaciÃ³n con CategorÃ­a
    descripcion CLOB,
    FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria)
);

-- Tabla Contactos
CREATE TABLE Contactos (
    id_contacto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- RelaciÃ³n con Locales
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    instagram VARCHAR2(100),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Reservas
CREATE TABLE Reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,  -- RelaciÃ³n con Usuarios
    id_local NUMBER,  -- RelaciÃ³n con Locales
    fecha DATE NOT NULL,
    hora VARCHAR2(10) NOT NULL,
    numero_personas NUMBER NOT NULL,
    descripcion VARCHAR2(200),
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla ReseÃ±as
CREATE TABLE Resenas (
    id_resena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,  -- RelaciÃ³n con Usuarios
    id_local NUMBER,  -- RelaciÃ³n con Locales
    calificacion NUMBER CHECK (calificacion BETWEEN 1 AND 5),
    comentario VARCHAR2(200),
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Fotos
CREATE TABLE Fotos (
    id_foto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER NOT NULL,  -- RelaciÃ³n con Locales
    ruta_foto VARCHAR2(255) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local),
    UNIQUE (id_local, id_foto)  -- Asegura combinaciones Ãºnicas de local y foto
);

-- Tabla Eventos Especiales
CREATE TABLE EventosEspeciales (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- RelaciÃ³n con Locales
    nombre_evento VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    fecha_evento DATE NOT NULL,
    hora_evento TIMESTAMP(0) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Promociones
CREATE TABLE Promociones (
    id_promocion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- RelaciÃ³n con Locales
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR2(50) DEFAULT 'Activa', -- Puede ser 'Activa', 'Expirada'
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla UbicaciÃ³n
CREATE TABLE Ubicacion (
    id_ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER NOT NULL,  -- RelaciÃ³n con Locales
    provincia VARCHAR2(50) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local),
    UNIQUE (id_local, id_ubicacion)  -- Asegura combinaciones Ãºnicas de local y ubicaciÃ³n
);

---------------------------------------------------
--INSERTs PARA PRUEBAS--
---------------------------------------------------

-- Insertar en CategorÃ­a
INSERT INTO Categoria (tipo) VALUES ('Restaurante');
INSERT INTO Categoria (tipo) VALUES ('Bar');

-- Insertar en Usuarios
INSERT INTO Usuarios (username, nombre, primer_apellido, segundo_apellido, correo, password, foto) VALUES ('weny', 'Wendy', 'Badilla', 'Carvajal', 'wendybadilla40@gmail.com', '123', 'https://www.myoutfie.com/historias/wp-content/uploads/2019/10/ropa-mujer-casual-1.jpg');
INSERT INTO Usuarios (username, nombre, primer_apellido, segundo_apellido, correo, password, foto) VALUES ('ste', 'Steven', 'Chacon', 'Camacho', 'stchch06@gmail.com', '123', 'https://faraisnake.com/wp-content/uploads/2024/01/image-36-820x1024.png');

-- Insertar en Locales
INSERT INTO Locales (nombre, id_categoria, descripcion) VALUES ('Zuntra', 2, 'Un pedacito de jungla de playa en BÂº Escalante');
INSERT INTO Locales (nombre, id_categoria, descripcion) VALUES ('Ahumaditos', 1, 'La mejor calidad en platillos ahumados y a la parrilla');

-- Insertar en Contactos
INSERT INTO Contactos (id_local, telefono, email, instagram) VALUES (1, '70856984', 'zuntra@gmail.com', '@zuntracr');
INSERT INTO Contactos (id_local, telefono, email, instagram) VALUES (2, '71799808', 'ahumado@gmail.com', '@ahumadictoscr');

-- Insertar en Reservas
INSERT INTO Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion) VALUES (1, 1, TO_DATE('2024-07-18', 'YYYY-MM-DD'), '05:00 pm', 4, 'Reserva para 4 personas');
INSERT INTO Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion) VALUES (2, 2, TO_DATE('2024-07-19', 'YYYY-MM-DD'), '06:00 pm', 2, 'Reserva para 2 personas');

-- Insertar en ReseÃ±as
INSERT INTO Resenas (id_usuario, id_local, calificacion, comentario) VALUES (1, 1, 5, 'Excelente servicio');
INSERT INTO Resenas (id_usuario, id_local, calificacion, comentario) VALUES (2, 2, 4, 'Muy buen lugar');

-- Insertar en Fotos
INSERT INTO Fotos (id_local, ruta_foto) VALUES (1, 'https://lh3.googleusercontent.com/p/AF1QipMrcbuz-ccUfjUWJtJ7Q545RtCdDSiiDPLgKcqk=s1360-w1360-h1020');
INSERT INTO Fotos (id_local, ruta_foto) VALUES (2, 'https://lh3.googleusercontent.com/p/AF1QipPR6U9O6l9P8Xo7vSs6n4ObgAllehEnVWyKxgQt=s1360-w1360-h1020');
INSERT INTO Fotos (id_local, ruta_foto) VALUES (2, 'https://jbarrelsmoker.com/cdn/shop/files/86bde1e6-f8da-4fcf-abb3-ea47b9176384_001af96c-c203-44b9-8693-c84b00539644.jpg?v=1715355189&width=1445');

-- Insertar en Eventos Especiales
INSERT INTO EventosEspeciales (id_local, nombre_evento, descripcion, fecha_evento, hora_evento) VALUES (1, 'Festival de MÃºsica Primavera', 'Ãšnete a nosotros para una celebraciÃ³n vibrante de la mÃºsica durante nuestro Festival de MÃºsica Primavera. Disfruta de actuaciones en vivo de bandas locales y artistas internacionales mientras te sumerges en un ambiente festivo con comida deliciosa y actividades para toda la familia.', TO_DATE('2024-07-20', 'YYYY-MM-DD'), TO_TIMESTAMP('20-07-2024 18:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO EventosEspeciales (id_local, nombre_evento, descripcion, fecha_evento, hora_evento) VALUES (2, 'Noche de Cocteles y Jazz', 'Ven a disfrutar de una noche elegante con nuestra Noche de Cocteles y Jazz. Degusta una selecciÃ³n exclusiva de cocteles artesanales preparados por nuestros expertos mixÃ³logos mientras te relajas con mÃºsica jazz en vivo. Un ambiente sofisticado y relajante para una velada inolvidable.', TO_DATE('2024-07-21', 'YYYY-MM-DD'), TO_TIMESTAMP('21-07-2024 19:00:00', 'DD-MM-YYYY HH24:MI:SS'));

-- Insertar en Promociones
INSERT INTO Promociones (id_local, nombre, descripcion, fecha_inicio, fecha_fin, estado) VALUES (1, 'Happy Hour', '2x1 en cocteles', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-31', 'YYYY-MM-DD'), 'Activa');
INSERT INTO Promociones (id_local, nombre, descripcion, fecha_inicio, fecha_fin, estado) VALUES (2, '10% Descuento', '10% de descuento al pagar con BN Tarjetas', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'Expirada');

-- Insertar en UbicaciÃ³n
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (1, 'San JosÃ©', 'Av. 7, Barrio Escalante');
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (2, 'Cartago', 'Centro en Cartago, 300 Metros al Sur, 100 Metros al Este, Del McDonaldÂ´s');
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (2, 'Alajuela', '1500 metros de la iglesia catÃ³lica del barrio San JosÃ©');

-----------------------------------

SELECT * FROM Ubicacion;
SELECT * FROM Categoria;
SELECT * FROM Usuarios;
SELECT * FROM Locales;
SELECT * FROM Contactos;
SELECT * FROM Reservas;
SELECT * FROM Resenas;
SELECT * FROM Fotos;
SELECT * FROM EventosEspeciales;
SELECT * FROM Promociones;

-------------------------------------

DROP TABLE Contactos CASCADE CONSTRAINTS;
DROP TABLE Reservas CASCADE CONSTRAINTS;
DROP TABLE Resenas CASCADE CONSTRAINTS;
DROP TABLE Fotos CASCADE CONSTRAINTS;
DROP TABLE EventosEspeciales CASCADE CONSTRAINTS;
DROP TABLE Promociones CASCADE CONSTRAINTS;
DROP TABLE Locales CASCADE CONSTRAINTS;
DROP TABLE Categoria CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;
DROP TABLE Ubicacion CASCADE CONSTRAINTS;


---------------------------------------------------
--PROCEDIMEINTOS ALMACENADOS--
---------------------------------------------------

-- SP para obtener todos los locales
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
           c.tipo AS tipo, 
           (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto
    FROM C##eataway.Locales l
    LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria;
END;

-- SP para obtener un local por ID
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerLocalPorID(
  p_id_local IN C##eataway.Locales.id_local%TYPE,
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
           c.tipo AS tipo, 
           (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto,
           co.telefono, co.email, co.instagram
    FROM C##eataway.Locales l
    LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria
    LEFT JOIN C##eataway.Contactos co ON l.id_local = co.id_local
    WHERE l.id_local = p_id_local;
END;

-- SP para obtener eventos especiales
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerEventosEspecialesSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT e.id_evento, e.nombre_evento, e.descripcion, e.fecha_evento, e.hora_evento, 
           l.nombre AS nombre_local
    FROM C##eataway.EventosEspeciales e
    LEFT JOIN C##eataway.Locales l ON e.id_local = l.id_local;
END;

-- SP para obtener todas las reseÃ±as de un local especÃ­fico con nombre completo de usuario y foto de usuario
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerResenasPorLocalSP(
    p_id_local IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT r.id_resena, r.id_local, r.calificacion, r.comentario,
           u.nombre || ' ' || u.primer_apellido || ' ' || u.segundo_apellido AS nombre_completo,
           u.username AS nombre_usuario,
           u.foto AS foto_usuario
    FROM C##eataway.Resenas r
    LEFT JOIN C##eataway.Usuarios u ON r.id_usuario = u.id_usuario
    WHERE r.id_local = p_id_local;
END;

-- SP para insertar una reseÃ±a
CREATE OR REPLACE PROCEDURE C##eataway.InsertarResenaSP(
    p_id_usuario IN C##eataway.Resenas.id_usuario%TYPE,
    p_id_local IN C##eataway.Resenas.id_local%TYPE,
    p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
    p_comentario IN C##eataway.Resenas.comentario%TYPE
) AS
BEGIN
    INSERT INTO C##eataway.Resenas (id_usuario, id_local, calificacion, comentario)
    VALUES (p_id_usuario, p_id_local, p_calificacion, p_comentario);
END;

-- SP para insertar una reserva
CREATE OR REPLACE PROCEDURE C##eataway.InsertarReservaSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_id_local IN C##eataway.Reservas.id_local%TYPE,
    p_fecha IN C##eataway.Reservas.fecha%TYPE,
    p_hora IN C##eataway.Reservas.hora%TYPE,
    p_numero_personas IN C##eataway.Reservas.numero_personas%TYPE,
    p_descripcion IN C##eataway.Reservas.descripcion%TYPE
) AS
BEGIN
    INSERT INTO C##eataway.Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion)
    VALUES (p_id_usuario, p_id_local, p_fecha, p_hora, p_numero_personas, p_descripcion);
END;

-- SP para obtener las reservas por id usuario
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerReservasPorUsuarioSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT r.id_reserva, r.id_usuario, r.id_local, r.fecha, r.hora, r.numero_personas, r.descripcion,
               l.nombre AS nombre_local
        FROM C##eataway.Reservas r
        LEFT JOIN C##eataway.Locales l ON r.id_local = l.id_local
        WHERE r.id_usuario = p_id_usuario;
END;

-- SP para eliminar una reserva
CREATE OR REPLACE PROCEDURE C##eataway.EliminarReservaSP(
    p_id_reserva IN NUMBER
) AS
BEGIN
    DELETE FROM C##eataway.Reservas
    WHERE id_reserva = p_id_reserva;
    COMMIT;
END;

--SP para recuperar todas las ubicaciones asociadas a un local especÃ­fico
CREATE OR REPLACE PROCEDURE ObtenerUbicacionesPorLocalSP(
    p_id_local IN Ubicacion.id_local%TYPE,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT id_ubicacion, id_local, provincia, direccion
        FROM Ubicacion
        WHERE id_local = p_id_local;
END ObtenerUbicacionesPorLocalSP;

--SP para Obtener Fotos por local
CREATE OR REPLACE PROCEDURE ObtenerFotosPorLocalSP(
    p_id_local IN Fotos.id_local%TYPE,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT id_foto, id_local, ruta_foto
    FROM Fotos
    WHERE id_local = p_id_local;
END ObtenerFotosPorLocalSP;

--SP para obtener los locales por tipo de local
CREATE OR REPLACE PROCEDURE ObtenerLocalesPorTipo(
  p_tipo_establecimiento IN Categoria.tipo%TYPE,
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
           c.tipo AS tipo, 
           (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto,
           co.telefono, co.email, co.instagram
    FROM C##eataway.Locales l
    LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria
    LEFT JOIN C##eataway.Contactos co ON l.id_local = co.id_local
    WHERE c.tipo = p_tipo_establecimiento;
END ObtenerLocalesPorTipo;

--SP para obtener las categorias que existen
CREATE OR REPLACE PROCEDURE ObtenerCategoriasSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_categoria, tipo
    FROM C##eataway.Categoria;
END;

--SP para obtener la reseÃ±as pos usuario
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerResenasPorUsuarioSP(
    p_id_usuario IN C##eataway.Resenas.id_usuario%TYPE,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT r.id_resena, r.id_usuario, r.id_local, r.calificacion, r.comentario,
               l.nombre AS nombre_local
        FROM C##eataway.Resenas r
        LEFT JOIN C##eataway.Locales l ON r.id_local = l.id_local
        WHERE r.id_usuario = p_id_usuario;
END;

-- SP para eliminar una reseÃ±a
CREATE OR REPLACE PROCEDURE C##eataway.EliminarResenaSP(
    p_id_resena IN NUMBER
) AS
BEGIN
    DELETE FROM C##eataway.Resenas
    WHERE id_resena = p_id_resena;
    COMMIT;
END;

--SP para actualizar una reseÃ±a
CREATE OR REPLACE PROCEDURE C##eataway.ActualizarResenaSP(
    p_id_resena IN C##eataway.Resenas.id_resena%TYPE,
    p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
    p_comentario IN C##eataway.Resenas.comentario%TYPE
) AS
BEGIN
    UPDATE C##eataway.Resenas
    SET calificacion = p_calificacion,
        comentario = p_comentario
    WHERE id_resena = p_id_resena;
END;

--SP para actualizar una reserva
CREATE OR REPLACE PROCEDURE ActualizarReservaSP(
    p_id_reserva IN C##eataway.Reservas.id_reserva%TYPE,
    p_fecha IN C##eataway.Reservas.fecha%TYPE,
    p_hora IN C##eataway.Reservas.hora%TYPE,
    p_numero_personas IN C##eataway.Reservas.numero_personas%TYPE,
    p_descripcion IN C##eataway.Reservas.descripcion%TYPE
) AS
BEGIN
    UPDATE C##eataway.Reservas
    SET fecha = p_fecha,
        hora = p_hora,
        numero_personas = p_numero_personas,
        descripcion = p_descripcion
    WHERE id_reserva = p_id_reserva;
END;

--SP para obtener las reservas por el id
CREATE OR REPLACE PROCEDURE ObtenerReservaPorId(
    p_id_reserva IN Reservas.id_reserva%TYPE,
    cur_reserva OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN cur_reserva FOR
        SELECT r.id_reserva,
               r.id_usuario,
               r.id_local,
               r.fecha,
               r.hora,
               r.numero_personas,
               r.descripcion,
               l.nombre AS nombre_local  
        FROM Reservas r
        JOIN Locales l ON r.id_local = l.id_local
        WHERE r.id_reserva = p_id_reserva;
END;

--SP obtener promociones activas
CREATE OR REPLACE PROCEDURE ObtenerPromocionesActivasSP(
    cur_promociones OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN cur_promociones FOR
    SELECT 
        p.id_promocion, p.id_local, p.nombre AS nombre_promocion,
        p.descripcion, p.fecha_inicio, p.fecha_fin, p.estado, l.nombre AS nombre_local,
        (SELECT f.ruta_foto
         FROM Fotos f
         WHERE f.id_local = l.id_local
         AND ROWNUM = 1) AS foto_local
    FROM 
        Promociones p
    JOIN 
        Locales l ON p.id_local = l.id_local
    WHERE 
        p.estado = 'Activa'
    ORDER BY 
        p.fecha_inicio DESC;
END;

--SP obtener promociones expiradas
CREATE OR REPLACE PROCEDURE ObtenerPromocionesExpiradasSP(
    cur_promociones OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN cur_promociones FOR
    SELECT 
        p.id_promocion, p.id_local, p.nombre AS nombre_promocion,
        p.descripcion, p.fecha_inicio, p.fecha_fin, p.estado, l.nombre AS nombre_local,
        (SELECT f.ruta_foto
         FROM Fotos f
         WHERE f.id_local = l.id_local
         AND ROWNUM = 1) AS foto_local
    FROM 
        Promociones p
    JOIN 
        Locales l ON p.id_local = l.id_local
    WHERE 
        p.estado = 'Expirada'
    ORDER BY 
        p.fecha_inicio DESC;
END;

-- SP para insertar un nuevo usuario
CREATE OR REPLACE PROCEDURE InsertarUsuarioSP(
    p_username IN Usuarios.username%TYPE,
    p_nombre IN Usuarios.nombre%TYPE,
    p_primer_apellido IN Usuarios.primer_apellido%TYPE,
    p_segundo_apellido IN Usuarios.segundo_apellido%TYPE,
    p_correo IN Usuarios.correo%TYPE,
    p_password IN Usuarios.password%TYPE,
    p_foto IN Usuarios.foto%TYPE
) AS
BEGIN
    INSERT INTO Usuarios (
        username, nombre, primer_apellido, segundo_apellido, correo, password, foto
    ) VALUES (
        p_username, p_nombre, p_primer_apellido, p_segundo_apellido, p_correo, p_password, p_foto
    );
END InsertarUsuarioSP;

-- SP para obtener un usuario por ID
CREATE OR REPLACE PROCEDURE ObtenerUsuarioPorIDSP(
    p_id_usuario IN Usuarios.id_usuario%TYPE,
    p_username OUT Usuarios.username%TYPE,
    p_nombre OUT Usuarios.nombre%TYPE,
    p_primer_apellido OUT Usuarios.primer_apellido%TYPE,
    p_segundo_apellido OUT Usuarios.segundo_apellido%TYPE,
    p_correo OUT Usuarios.correo%TYPE,
    p_password OUT Usuarios.password%TYPE,
    p_foto OUT Usuarios.foto%TYPE
) AS
BEGIN
    SELECT username, nombre, primer_apellido, segundo_apellido, correo, password, foto
    INTO p_username, p_nombre, p_primer_apellido, p_segundo_apellido, p_correo, p_password, p_foto
    FROM Usuarios
    WHERE id_usuario = p_id_usuario;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_username := NULL;
        p_nombre := NULL;
        p_primer_apellido := NULL;
        p_segundo_apellido := NULL;
        p_correo := NULL;
        p_password := NULL;
        p_foto := NULL;
END ObtenerUsuarioPorIDSP;

-- SP para actualizar un usuario existente
CREATE OR REPLACE PROCEDURE ActualizarUsuarioSP(
    p_id_usuario IN Usuarios.id_usuario%TYPE,
    p_username IN Usuarios.username%TYPE,
    p_nombre IN Usuarios.nombre%TYPE,
    p_primer_apellido IN Usuarios.primer_apellido%TYPE,
    p_segundo_apellido IN Usuarios.segundo_apellido%TYPE,
    p_correo IN Usuarios.correo%TYPE,
    p_password IN Usuarios.password%TYPE,
    p_foto IN Usuarios.foto%TYPE
) AS
BEGIN
    UPDATE Usuarios
    SET
        username = p_username,
        nombre = p_nombre,
        primer_apellido = p_primer_apellido,
        segundo_apellido = p_segundo_apellido,
        correo = p_correo,
        password = p_password,
        foto = p_foto
    WHERE id_usuario = p_id_usuario;
END ActualizarUsuarioSP;

-- SP para eliminar un usuario por ID
CREATE OR REPLACE PROCEDURE EliminarUsuarioSP(
    p_id_usuario IN Usuarios.id_usuario%TYPE
) AS
BEGIN
    DELETE FROM Usuarios
    WHERE id_usuario = p_id_usuario;
END EliminarUsuarioSP;

-- SP para insertar un nuevo local junto con su contacto, una foto y ubicación
CREATE OR REPLACE PROCEDURE InsertarLocalSP(
    p_nombre IN Locales.nombre%TYPE,
    p_id_categoria IN Locales.id_categoria%TYPE,
    p_descripcion IN Locales.descripcion%TYPE,
    p_contacto_telefono IN Contactos.telefono%TYPE,
    p_contacto_email IN Contactos.email%TYPE,
    p_contacto_instagram IN Contactos.instagram%TYPE,
    p_foto IN Fotos.ruta_foto%TYPE,  -- URL de la foto
    p_provincia IN Ubicacion.provincia%TYPE,
    p_direccion IN Ubicacion.direccion%TYPE
) AS
    v_id_local Locales.id_local%TYPE;
BEGIN
    -- Insertar el nuevo local
    INSERT INTO Locales (nombre, id_categoria, descripcion)
    VALUES (p_nombre, p_id_categoria, p_descripcion)
    RETURNING id_local INTO v_id_local;

    -- Insertar el contacto asociado al nuevo local
    INSERT INTO Contactos (id_local, telefono, email, instagram)
    VALUES (v_id_local, p_contacto_telefono, p_contacto_email, p_contacto_instagram);

    -- Insertar la foto asociada al nuevo local
    INSERT INTO Fotos (id_local, ruta_foto)
    VALUES (v_id_local, p_foto);

    -- Insertar la ubicación asociada al nuevo local
    INSERT INTO Ubicacion (id_local, provincia, direccion)
    VALUES (v_id_local, p_provincia, p_direccion);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END InsertarLocalSP;

-- SP para agregar varias fotos a un local
CREATE OR REPLACE PROCEDURE AgregarFotosALocalSP(
    p_id_local IN Fotos.id_local%TYPE,  
    p_fotos IN SYS.ODCIVARCHAR2LIST 
) AS
BEGIN
    FOR i IN 1 .. p_fotos.COUNT LOOP
        INSERT INTO Fotos (id_local, ruta_foto)
        VALUES (p_id_local, p_fotos(i));
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END AgregarFotosALocalSP;

-- SP para agregar varias ubicaciones a un local
CREATE OR REPLACE PROCEDURE AgregarUbicacionesALocalSP(
    p_id_local IN Ubicacion.id_local%TYPE,
    p_provincias IN SYS.ODCIVARCHAR2LIST,
    p_direcciones IN SYS.ODCIVARCHAR2LIST 
) AS
BEGIN
    IF p_provincias.COUNT != p_direcciones.COUNT THEN
        RAISE_APPLICATION_ERROR(-20001, 'Las listas de provincias y direcciones deben tener el mismo tamaño.');
    END IF;
    
    FOR i IN 1 .. p_provincias.COUNT LOOP
        INSERT INTO Ubicacion (id_local, provincia, direccion)
        VALUES (p_id_local, p_provincias(i), p_direcciones(i));
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END AgregarUbicacionesALocalSP;



---------------------------------------------------
------PAQUETES------
---------------------------------------------------

--*****Paquete para Obtener Locales*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_LOCAL_OBTENER AS
  PROCEDURE ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR);
  PROCEDURE ObtenerLocalPorID(
    p_id_local IN C##eataway.Locales.id_local%TYPE,
    p_cursor OUT SYS_REFCURSOR
  );
END PCK_EATAWAY_LOCAL_OBTENER;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_LOCAL_OBTENER AS
  PROCEDURE ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
             c.tipo AS tipo, 
             (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto
      FROM C##eataway.Locales l
      LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria;
  END;

  PROCEDURE ObtenerLocalPorID(
    p_id_local IN C##eataway.Locales.id_local%TYPE,
    p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
             c.tipo AS tipo, 
             (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto,
             co.telefono, co.email, co.instagram
      FROM C##eataway.Locales l
      LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria
      LEFT JOIN C##eataway.Contactos co ON l.id_local = co.id_local
      WHERE l.id_local = p_id_local;
  END;
END PCK_EATAWAY_LOCAL_OBTENER;

--*****Paquete para Obtener Eventos Especiales*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_EVENTO_OBTENER AS
  PROCEDURE ObtenerEventosEspecialesSP(p_cursor OUT SYS_REFCURSOR);
END PCK_EATAWAY_EVENTO_OBTENER;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_EVENTO_OBTENER AS
  PROCEDURE ObtenerEventosEspecialesSP(p_cursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT e.id_evento, e.nombre_evento, e.descripcion, e.fecha_evento, e.hora_evento, 
             l.nombre AS nombre_local
      FROM C##eataway.EventosEspeciales e
      LEFT JOIN C##eataway.Locales l ON e.id_local = l.id_local;
  END;
END PCK_EATAWAY_EVENTO_OBTENER;

--*****Paquete para Obtener ReseÃ±as*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESENA_OBTENER AS
  PROCEDURE ObtenerResenasPorLocalSP(
    p_id_local IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
  );
END PCK_EATAWAY_RESENA_OBTENER;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESENA_OBTENER AS
  PROCEDURE ObtenerResenasPorLocalSP(
    p_id_local IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT r.id_resena, r.id_local, r.calificacion, r.comentario,
             u.nombre || ' ' || u.primer_apellido || ' ' || u.segundo_apellido AS nombre_completo,
             u.username AS nombre_usuario,
             u.foto AS foto_usuario
      FROM C##eataway.Resenas r
      LEFT JOIN C##eataway.Usuarios u ON r.id_usuario = u.id_usuario
      WHERE r.id_local = p_id_local;
  END;
END PCK_EATAWAY_RESENA_OBTENER;

--*****Paquete para Insertar ReseÃ±as*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESENA_INSERTAR AS
  PROCEDURE InsertarResenaSP(
    p_id_usuario IN C##eataway.Resenas.id_usuario%TYPE,
    p_id_local IN C##eataway.Resenas.id_local%TYPE,
    p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
    p_comentario IN C##eataway.Resenas.comentario%TYPE
  );
END PCK_EATAWAY_RESENA_INSERTAR;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESENA_INSERTAR AS
  PROCEDURE InsertarResenaSP(
    p_id_usuario IN C##eataway.Resenas.id_usuario%TYPE,
    p_id_local IN C##eataway.Resenas.id_local%TYPE,
    p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
    p_comentario IN C##eataway.Resenas.comentario%TYPE
  ) AS
  BEGIN
    INSERT INTO C##eataway.Resenas (id_usuario, id_local, calificacion, comentario)
    VALUES (p_id_usuario, p_id_local, p_calificacion, p_comentario);
  END;
END PCK_EATAWAY_RESENA_INSERTAR;

--*****Paquete para Insertar Reservas*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESERVA_INSERTAR AS
  PROCEDURE InsertarReservaSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_id_local IN C##eataway.Reservas.id_local%TYPE,
    p_fecha IN C##eataway.Reservas.fecha%TYPE,
    p_hora IN C##eataway.Reservas.hora%TYPE,
    p_numero_personas IN C##eataway.Reservas.numero_personas%TYPE,
    p_descripcion IN C##eataway.Reservas.descripcion%TYPE
  );
END PCK_EATAWAY_RESERVA_INSERTAR;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESERVA_INSERTAR AS
  PROCEDURE InsertarReservaSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_id_local IN C##eataway.Reservas.id_local%TYPE,
    p_fecha IN C##eataway.Reservas.fecha%TYPE,
    p_hora IN C##eataway.Reservas.hora%TYPE,
    p_numero_personas IN C##eataway.Reservas.numero_personas%TYPE,
    p_descripcion IN C##eataway.Reservas.descripcion%TYPE
  ) AS
  BEGIN
    INSERT INTO C##eataway.Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion)
    VALUES (p_id_usuario, p_id_local, p_fecha, p_hora, p_numero_personas, p_descripcion);
  END;
END PCK_EATAWAY_RESERVA_INSERTAR;

--*****Paquete para Obtener Reservas por Usuario*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESERVA_OBTENER AS
  PROCEDURE ObtenerReservasPorUsuarioSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_cursor OUT SYS_REFCURSOR
  );
END PCK_EATAWAY_RESERVA_OBTENER;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESERVA_OBTENER AS
  PROCEDURE ObtenerReservasPorUsuarioSP(
    p_id_usuario IN C##eataway.Reservas.id_usuario%TYPE,
    p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT r.id_reserva, r.id_usuario, r.id_local, r.fecha, r.hora, r.numero_personas, r.descripcion,
             l.nombre AS nombre_local
      FROM C##eataway.Reservas r
      LEFT JOIN C##eataway.Locales l ON r.id_local = l.id_local
      WHERE r.id_usuario = p_id_usuario;
  END;
END PCK_EATAWAY_RESERVA_OBTENER;

--*****Paquete para Eliminar Reservas*****-
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESERVA_ELIMINAR AS
  PROCEDURE EliminarReservaSP(
    p_id_reserva IN NUMBER
  );
END PCK_EATAWAY_RESERVA_ELIMINAR;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESERVA_ELIMINAR AS
  PROCEDURE EliminarReservaSP(
    p_id_reserva IN NUMBER
  ) AS
  BEGIN
    DELETE FROM C##eataway.Reservas
    WHERE id_reserva = p_id_reserva;
    COMMIT;
  END;
END PCK_EATAWAY_RESERVA_ELIMINAR;

--*****Paquete para obtener los locale por categoria*****--
CREATE OR REPLACE PACKAGE PCK_EATAWAY_LOCAL_OBTENER_TIPO AS
    PROCEDURE ObtenerLocalesPorTipo(
        tipoEstablecimiento IN VARCHAR2,
        localesCursor OUT SYS_REFCURSOR
    );
END PCK_EATAWAY_LOCAL_OBTENER_TIPO;

CREATE OR REPLACE PACKAGE BODY PCK_EATAWAY_LOCAL_OBTENER_TIPO AS

    PROCEDURE ObtenerLocalesPorTipo(
        tipoEstablecimiento IN VARCHAR2,
        localesCursor OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN localesCursor FOR
        SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
               c.tipo AS tipo, 
               (SELECT ruta_foto FROM Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto,
               co.telefono, co.email, co.instagram
        FROM Locales l
        LEFT JOIN Categoria c ON l.id_categoria = c.id_categoria
        LEFT JOIN Contactos co ON l.id_local = co.id_local
        WHERE c.tipo = tipoEstablecimiento;
    END ObtenerLocalesPorTipo;

END PCK_EATAWAY_LOCAL_OBTENER_TIPO;

--*****Paquete para eliminar reseÃ±as*****--
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESENA_ELIMINAR IS
    PROCEDURE EliminarResenaSP(p_id_resena IN NUMBER);
END PCK_EATAWAY_RESENA_ELIMINAR;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESENA_ELIMINAR IS

    PROCEDURE EliminarResenaSP(p_id_resena IN NUMBER) IS
    BEGIN
        DELETE FROM C##eataway.Resenas
        WHERE id_resena = p_id_resena;
        COMMIT;
    END EliminarResenaSP;

END PCK_EATAWAY_RESENA_ELIMINAR;

--*****Paquete para actualizar reseÃ±as*****--
CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_RESENA_ACTUALIZAR IS
    PROCEDURE ActualizarResenaSP(
        p_id_resena IN C##eataway.Resenas.id_resena%TYPE,
        p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
        p_comentario IN C##eataway.Resenas.comentario%TYPE
    );
END PCK_EATAWAY_RESENA_ACTUALIZAR;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_RESENA_ACTUALIZAR IS

    PROCEDURE ActualizarResenaSP(
        p_id_resena IN C##eataway.Resenas.id_resena%TYPE,
        p_calificacion IN C##eataway.Resenas.calificacion%TYPE,
        p_comentario IN C##eataway.Resenas.comentario%TYPE
    ) IS
    BEGIN
        UPDATE C##eataway.Resenas
        SET calificacion = p_calificacion,
            comentario = p_comentario
        WHERE id_resena = p_id_resena;
    END ActualizarResenaSP;

END PCK_EATAWAY_RESENA_ACTUALIZAR;

--*****Paquete para *****--


---------------------------------------------------
--VISTAS--
---------------------------------------------------

-- Vista de usuarios con sus reseÃ±as y calificaciones
CREATE VIEW Vista_Usuarios_Resenas AS
SELECT u.id_usuario, u.username, u.nombre, u.primer_apellido, u.correo, r.calificacion, r.comentario
FROM Usuarios u
JOIN Resenas r ON u.id_usuario = r.id_usuario;

-- Vista de locales con sus eventos especiales
CREATE VIEW Vista_Locales_Eventos AS
SELECT l.id_local, l.nombre AS nombre_local, e.nombre_evento, e.descripcion, e.fecha_evento, e.hora_evento
FROM Locales l
JOIN EventosEspeciales e ON l.id_local = e.id_local;

-- Vista de promociones activas para cada local
CREATE VIEW Vista_Promociones_Activas AS
SELECT l.nombre AS nombre_local, p.nombre AS nombre_promocion, p.descripcion, p.fecha_inicio, p.fecha_fin
FROM Locales l
JOIN Promociones p ON l.id_local = p.id_local
WHERE p.estado = 'Activa';

-- Vista de contactos de locales
CREATE VIEW Vista_Contactos_Locales AS
SELECT l.nombre AS nombre_local, c.telefono, c.email, c.instagram
FROM Locales l
JOIN Contactos c ON l.id_local = c.id_local;

-- Vista de usuarios con sus reservas
CREATE VIEW Vista_Usuarios_Reservas AS
SELECT u.id_usuario, u.username, u.nombre, r.fecha, r.hora, r.numero_personas, r.descripcion
FROM Usuarios u
JOIN Reservas r ON u.id_usuario = r.id_usuario;

-- Vista de locales con sus reseÃ±as y calificaciones promedio
CREATE VIEW Vista_Locales_Calificacion_Promedio AS
SELECT l.id_local, l.nombre AS nombre_local, AVG(r.calificacion) AS calificacion_promedio
FROM Locales l
JOIN Resenas r ON l.id_local = r.id_local
GROUP BY l.id_local, l.nombre;

-- Vista de fotos de locales
CREATE VIEW Vista_Fotos_Locales AS
SELECT l.id_local, l.nombre AS nombre_local, f.ruta_foto
FROM Locales l
JOIN Fotos f ON l.id_local = f.id_local;

-- Vista de ubicaciones de locales
CREATE VIEW Vista_Ubicaciones_Locales AS
SELECT l.id_local, l.nombre AS nombre_local, u.provincia, u.direccion
FROM Locales l
JOIN Ubicacion u ON l.id_local = u.id_local;

-- Vista de reservas para un local especÃ­fico (ID 1)
CREATE VIEW Vista_Reservas_Local_Especifico AS
SELECT r.id_reserva, r.fecha, r.hora, r.numero_personas, r.descripcion, u.username
FROM Reservas r
JOIN Usuarios u ON r.id_usuario = u.id_usuario
WHERE r.id_local = 1;

-- Vista de detalles completos de un local
CREATE VIEW Vista_Detalles_Local AS
SELECT l.id_local, l.nombre AS nombre_local, c.tipo AS categoria, 
       con.telefono, con.email, con.instagram, 
       u.provincia, u.direccion,
       e.nombre_evento, e.fecha_evento, e.hora_evento
FROM Locales l
LEFT JOIN Categoria c ON l.id_categoria = c.id_categoria
LEFT JOIN Contactos con ON l.id_local = con.id_local
LEFT JOIN Ubicacion u ON l.id_local = u.id_local
LEFT JOIN EventosEspeciales e ON l.id_local = e.id_local;

---------------------------------------------------
--FUNCIONES--
---------------------------------------------------

-- Función para obtener la información de un usuario por su ID
CREATE OR REPLACE FUNCTION obtener_informacion_usuario(p_id_usuario NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Usuarios WHERE id_usuario = p_id_usuario;
    RETURN ref_cursor;
END;

-- Función para obtener la información de un local por su ID
CREATE OR REPLACE FUNCTION obtener_informacion_local(p_id_local NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Locales WHERE id_local = p_id_local;
    RETURN ref_cursor;
END;

-- Función para calcular el promedio de calificación de un local
CREATE OR REPLACE FUNCTION calcular_promedio_calificacion(p_id_local NUMBER) 
RETURN NUMBER AS
    avg_calificacion NUMBER;
BEGIN
    SELECT AVG(calificacion) INTO avg_calificacion
    FROM Resenas
    WHERE id_local = p_id_local;
    RETURN avg_calificacion;
END;

-- Función para contar el número de reservas en una fecha específica
CREATE OR REPLACE FUNCTION contar_reservas_fecha(p_fecha DATE) 
RETURN NUMBER AS
    total_reservas NUMBER;
BEGIN
    SELECT COUNT(*) INTO total_reservas
    FROM Reservas
    WHERE fecha = p_fecha;
    RETURN total_reservas;
END;

-- Función para obtener eventos especiales en una fecha específica
CREATE OR REPLACE FUNCTION obtener_eventos_especiales(p_fecha DATE) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM EventosEspeciales 
    WHERE fecha_evento = p_fecha;
    RETURN ref_cursor;
END;

-- Función para obtener todas las fotos de un local
CREATE OR REPLACE FUNCTION obtener_fotos_local(p_id_local NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Fotos WHERE id_local = p_id_local;
    RETURN ref_cursor;
END;

-- Función para obtener la ubicación de un local
CREATE OR REPLACE FUNCTION obtener_ubicacion_local(p_id_local NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Ubicacion WHERE id_local = p_id_local;
    RETURN ref_cursor;
END;

-- Función para obtener promociones activas en un local
CREATE OR REPLACE FUNCTION obtener_promociones_activas(p_id_local NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Promociones 
    WHERE id_local = p_id_local AND estado = 'Activa';
    RETURN ref_cursor;
END;

-- Función para validar si un usuario tiene reservas en un local
CREATE OR REPLACE FUNCTION tiene_reservas_local(p_id_usuario NUMBER, p_id_local NUMBER) 
RETURN BOOLEAN AS
    total_reservas NUMBER;
BEGIN
    -- Contar el número de reservas para el usuario en el local especificado
    SELECT COUNT(*) INTO total_reservas
    FROM Reservas
    WHERE id_usuario = p_id_usuario AND id_local = p_id_local;
    
    -- Devolver TRUE si hay reservas, FALSE en caso contrario
    RETURN total_reservas > 0;
END;

-- Función para obtener los datos de contacto de un local
CREATE OR REPLACE FUNCTION obtener_contactos_local(p_id_local NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Contactos WHERE id_local = p_id_local;
    RETURN ref_cursor;
END;

-- Función para contar el número de reseñas para un local
CREATE OR REPLACE FUNCTION contar_resenas_local(p_id_local NUMBER) 
RETURN NUMBER AS
    total_resenas NUMBER;
BEGIN
    SELECT COUNT(*) INTO total_resenas
    FROM Resenas
    WHERE id_local = p_id_local;
    RETURN total_resenas;
END;

-- Función para obtener usuarios por nombre (parcial)
CREATE OR REPLACE FUNCTION obtener_usuarios_por_nombre(p_nombre VARCHAR2) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Usuarios WHERE nombre LIKE '%' || p_nombre || '%';
    RETURN ref_cursor;
END;

-- Función para obtener locales por categoría
CREATE OR REPLACE FUNCTION obtener_locales_por_categoria(p_id_categoria NUMBER) 
RETURN SYS_REFCURSOR AS
    ref_cursor SYS_REFCURSOR;
BEGIN
    OPEN ref_cursor FOR 
    SELECT * FROM Locales WHERE id_categoria = p_id_categoria;
    RETURN ref_cursor;
END;

--Función para calcular el promedio de número de personas por reserva en el local especificado
CREATE OR REPLACE FUNCTION promedio_personas_por_reserva(p_id_local NUMBER)
RETURN NUMBER AS
    promedio NUMBER;
BEGIN    
    SELECT AVG(numero_personas) INTO promedio
    FROM Reservas
    WHERE id_local = p_id_local;

    RETURN promedio;
END;

--Función para calcular el promedio de las calificaciones para el local especificado
CREATE OR REPLACE FUNCTION calificacion_media_local(p_id_local NUMBER)
RETURN NUMBER AS
    promedio_calificacion NUMBER;
BEGIN
    SELECT AVG(calificacion) INTO promedio_calificacion
    FROM Resenas
    WHERE id_local = p_id_local;

    RETURN promedio_calificacion;
END;

--Función para encontrar la categoría con el mayor número de reservas
CREATE OR REPLACE FUNCTION categoria_mas_reservada
RETURN VARCHAR2 AS
    v_categoria VARCHAR2(50);
BEGIN    
    SELECT c.tipo
    INTO v_categoria
    FROM Categoria c
    JOIN Locales l ON c.id_categoria = l.id_categoria
    JOIN Reservas r ON l.id_local = r.id_local
    GROUP BY c.tipo
    ORDER BY COUNT(r.id_reserva) DESC
    FETCH FIRST 1 ROW ONLY;

    RETURN v_categoria;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;

---------------------------------------------------
--TRIGGERS--
---------------------------------------------------

--Trigger asegura que las reservas no se puedan hacer para fechas anteriores a la fecha actual.
CREATE OR REPLACE TRIGGER trg_check_fecha_reserva
BEFORE INSERT ON Reservas
FOR EACH ROW
BEGIN
    IF :NEW.fecha < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede hacer una reserva para una fecha pasada.');
    END IF;
END;

--Trigger si se intenta insertar una calificación fuera del rango.
CREATE OR REPLACE TRIGGER trg_validar_calificacion
BEFORE INSERT OR UPDATE ON Resenas
FOR EACH ROW
BEGIN
    IF :NEW.calificacion < 1 OR :NEW.calificacion > 5 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La calificación debe estar entre 1 y 5.');
    END IF;
END;

--Trigger para actualizar el estado de las promociones que ya han pasado su fecha de fin
CREATE OR REPLACE TRIGGER trg_actualizar_estado_promociones
AFTER INSERT OR UPDATE ON Promociones
FOR EACH ROW
BEGIN
    IF :NEW.fecha_fin < TRUNC(SYSDATE) THEN
        UPDATE Promociones
        SET estado = 'Expirada'
        WHERE id_promocion = :NEW.id_promocion;
    END IF;
END;

--Trigger que verifica si un local ya tiene un número máximo de 10 fotos
CREATE OR REPLACE TRIGGER trg_limitar_fotos_por_local
BEFORE INSERT ON Fotos
FOR EACH ROW
DECLARE
    cantidad_fotos NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cantidad_fotos
    FROM Fotos
    WHERE id_local = :NEW.id_local;

    IF cantidad_fotos >= 10 THEN
        RAISE_APPLICATION_ERROR(-20006, 'Se ha alcanzado el límite de 10 fotos por local.');
    END IF;
END;

--Trigger para restringir la modificación de la hora de reserva si la fecha es en el pasado
CREATE OR REPLACE TRIGGER trg_restringir_modificacion_hora_reserva
BEFORE UPDATE ON Reservas
FOR EACH ROW
BEGIN
    IF :NEW.fecha < TRUNC(SYSDATE) AND :OLD.fecha < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20008, 'No se puede modificar la hora de una reserva para una fecha que ya ha pasado.');
    END IF;
END;


