/*CONECTADO A SQL PLUS*/

CONNECT / AS SYSDBA

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- CREACIÓN DEL USUARIO
CREATE USER C##eataway IDENTIFIED BY sws2024;

-- ASIGNACIÓN DE PRIVILEGIOS AL USUARIO
GRANT CONNECT TO C##eataway;

GRANT ALL PRIVILEGES TO C##eataway;

-----------------------------------------------
--CREACION DE LAS TABLAS--
-------------------------------------------------

-- Tabla Categoría
CREATE TABLE Categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL
);

-- Tabla Usuarios
CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    primer_apellido VARCHAR2(50) NOT NULL,
    segundo_apellido VARCHAR2(50),
    correo VARCHAR2(100) NOT NULL UNIQUE,
    password varchar(200) NOT NULL,
    foto VARCHAR2(255)
);

-- Tabla Locales
CREATE TABLE Locales (
    id_local NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    id_categoria NUMBER,  -- Relación con Categoría
    descripcion CLOB,
    FOREIGN KEY (id_categoria) REFERENCES Categoria(id_categoria)
);

-- Tabla Contactos
CREATE TABLE Contactos (
    id_contacto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- Relación con Locales
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    instagram VARCHAR2(100),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Reservas
CREATE TABLE Reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,  -- Relación con Usuarios
    id_local NUMBER,  -- Relación con Locales
    fecha DATE NOT NULL,
    hora TIMESTAMP(0) NOT NULL,
    numero_personas NUMBER NOT NULL,
    descripcion CLOB,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Reseñas
CREATE TABLE Resenas (
    id_resena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,  -- Relación con Usuarios
    id_local NUMBER,  -- Relación con Locales
    calificacion NUMBER CHECK (calificacion BETWEEN 1 AND 5),
    comentario CLOB,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Fotos
CREATE TABLE Fotos (
    id_foto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER NOT NULL,  -- Relación con Locales
    ruta_foto VARCHAR2(255) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local),
    UNIQUE (id_local, id_foto)  -- Asegura combinaciones únicas de local y foto
);

-- Tabla Eventos Especiales
CREATE TABLE EventosEspeciales (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- Relación con Locales
    nombre_evento VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    fecha_evento DATE NOT NULL,
    hora_evento TIMESTAMP(0) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Promociones
CREATE TABLE Promociones (
    id_promocion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER,  -- Relación con Locales
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR2(50) DEFAULT 'Activa', -- Puede ser 'Activa', 'Expirada'
    FOREIGN KEY (id_local) REFERENCES Locales(id_local)
);

-- Tabla Ubicación
CREATE TABLE Ubicacion (
    id_ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local NUMBER NOT NULL,  -- Relación con Locales
    provincia VARCHAR2(50) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    FOREIGN KEY (id_local) REFERENCES Locales(id_local),
    UNIQUE (id_local, id_ubicacion)  -- Asegura combinaciones únicas de local y ubicación
);

---------------------------------------------------
--INSERTs PARA PRUEBAS--
---------------------------------------------------

-- Insertar en Categoría
INSERT INTO Categoria (tipo) VALUES ('Restaurante');
INSERT INTO Categoria (tipo) VALUES ('Bar');

-- Insertar en Usuarios
INSERT INTO Usuarios (username, nombre, primer_apellido, segundo_apellido, correo, password, foto) VALUES ('weny', 'Wendy', 'Badilla', 'Carvajal', 'wendybadilla40@gmail.com', '123', '');
INSERT INTO Usuarios (username, nombre, primer_apellido, segundo_apellido, correo, password, foto) VALUES ('ste', 'Steven', 'Chacon', 'Camacho', 'stchch06@gmail.com', '123', '');

-- Insertar en Locales
INSERT INTO Locales (nombre, id_categoria, descripcion) VALUES ('Zuntra', 1, 'Un pedacito de jungla de playa en Bº Escalante');
INSERT INTO Locales (nombre, id_categoria, descripcion) VALUES ('Ahumaditos', 2, 'La mejor calidad en platillos ahumados y a la parrilla');

-- Insertar en Contactos
INSERT INTO Contactos (id_local, telefono, email, instagram) VALUES (1, '70856984', 'zuntra@gmail.com', '@zuntracr');
INSERT INTO Contactos (id_local, telefono, email, instagram) VALUES (2, '71799808', 'ahumado@gmail.com', '@ahumadictoscr');

-- Insertar en Reservas
INSERT INTO Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion) VALUES (1, 1, TO_DATE('2024-07-18', 'YYYY-MM-DD'), TO_TIMESTAMP('18-07-2024 19:00:00', 'DD-MM-YYYY HH24:MI:SS'), 4, 'Reserva para 4 personas');
INSERT INTO Reservas (id_usuario, id_local, fecha, hora, numero_personas, descripcion) VALUES (2, 2, TO_DATE('2024-07-19', 'YYYY-MM-DD'), TO_TIMESTAMP('19-07-2024 20:00:00', 'DD-MM-YYYY HH24:MI:SS'), 2, 'Reserva para 2 personas');

-- Insertar en Reseñas
INSERT INTO Resenas (id_usuario, id_local, calificacion, comentario) VALUES (1, 1, 5, 'Excelente servicio');
INSERT INTO Resenas (id_usuario, id_local, calificacion, comentario) VALUES (2, 2, 4, 'Muy buen lugar');

-- Insertar en Fotos
INSERT INTO Fotos (id_local, ruta_foto) VALUES (1, 'https://lh3.googleusercontent.com/p/AF1QipMrcbuz-ccUfjUWJtJ7Q545RtCdDSiiDPLgKcqk=s1360-w1360-h1020');
INSERT INTO Fotos (id_local, ruta_foto) VALUES (2, 'https://lh3.googleusercontent.com/p/AF1QipPR6U9O6l9P8Xo7vSs6n4ObgAllehEnVWyKxgQt=s1360-w1360-h1020');

-- Insertar en Eventos Especiales
INSERT INTO EventosEspeciales (id_local, nombre_evento, descripcion, fecha_evento, hora_evento) VALUES (1, 'Evento 1', 'Descripción del Evento 1', TO_DATE('2024-07-20', 'YYYY-MM-DD'), TO_TIMESTAMP('20-07-2024 18:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO EventosEspeciales (id_local, nombre_evento, descripcion, fecha_evento, hora_evento) VALUES (2, 'Evento 2', 'Descripción del Evento 2', TO_DATE('2024-07-21', 'YYYY-MM-DD'), TO_TIMESTAMP('21-07-2024 19:00:00', 'DD-MM-YYYY HH24:MI:SS'));

-- Insertar en Promociones
INSERT INTO Promociones (id_local, nombre, descripcion, fecha_inicio, fecha_fin, estado) VALUES (1, 'Happy Hour', '2x1 en cocteles', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-31', 'YYYY-MM-DD'), 'Activa');
INSERT INTO Promociones (id_local, nombre, descripcion, fecha_inicio, fecha_fin, estado) VALUES (2, '10% Descuento', '10% de descuento al pagar con BN Tarjetas', TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'Expirada');

-- Insertar en Ubicación
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (1, 'San José', 'Av. 7, Barrio Escalante');
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (2, 'Cartago', '1500 metros de la iglesia católica del barrio San José');
INSERT INTO Ubicacion (id_local, provincia, direccion) VALUES (2, 'Alajuela', '1500 metros de la iglesia católica del barrio San José');

-----------------------------------

SELECT * FROM Ubicacion WHERE id_local = 2;
SELECT * FROM Categoria;
SELECT * FROM Usuarios;
SELECT * FROM Locales;
SELECT * FROM Contactos;
SELECT * FROM Reservas;
SELECT * FROM Resenas;
SELECT * FROM Fotos;
SELECT * FROM EventosEspeciales;
SELECT * FROM Promociones;

-------------------------------------

DROP TABLE Contactos CASCADE CONSTRAINTS;
DROP TABLE Reservas CASCADE CONSTRAINTS;
DROP TABLE Resenas CASCADE CONSTRAINTS;
DROP TABLE Fotos CASCADE CONSTRAINTS;
DROP TABLE EventosEspeciales CASCADE CONSTRAINTS;
DROP TABLE Promociones CASCADE CONSTRAINTS;
DROP TABLE Locales CASCADE CONSTRAINTS;
DROP TABLE Categoria CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;
DROP TABLE Ubicacion CASCADE CONSTRAINTS;

---------------------------------------------------
--PROCEDIMEINTOS ALMACENADOS--
---------------------------------------------------

--SP para obtener todos los locales
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
           c.tipo AS tipo, 
           (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto
    FROM C##eataway.Locales l
    LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria;
END;

CREATE OR REPLACE PACKAGE C##eataway.PCK_EATAWAY_LOCALES_OBTENER AS
  PROCEDURE ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR);
END PCK_EATAWAY_LOCALES_OBTENER;

CREATE OR REPLACE PACKAGE BODY C##eataway.PCK_EATAWAY_LOCALES_OBTENER AS
  PROCEDURE ObtenerLocalesSP(p_cursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_cursor FOR
      SELECT l.id_local, l.nombre, l.id_categoria, l.descripcion, 
           c.tipo AS tipo, 
           (SELECT ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto
    FROM C##eataway.Locales l
    LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria;
  END;
END PCK_EATAWAY_LOCALES_OBTENER;

DECLARE
  v_cursor SYS_REFCURSOR;
BEGIN
  C##eataway.PCK_EATAWAY_LOCALES_OBTENER.ObtenerLocalesSP(v_cursor);
END;

---------------------------------------------------

--Sp para obtener usuarios
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerUsuariosSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_usuario, username, nombre, primer_apellido, segundo_apellido, correo, foto
    FROM C##eataway.Usuarios;
END;

---------------------------------------------------

--Obtener Reservas por Usuario (id_usuario)
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerReservasPorUsuarioSP(p_usuario_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT r.id_reserva, r.id_local, l.nombre AS local_nombre, r.fecha, r.hora, r.numero_personas, r.descripcion
    FROM C##eataway.Reservas r
    JOIN C##eataway.Locales l ON r.id_local = l.id_local
    WHERE r.id_usuario = p_usuario_id;
END;

---------------------------------------------------

--Obtener reseñas por local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerResenasPorLocalSP(p_local_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT r.id_resena, r.id_usuario, u.nombre || ' ' || u.primer_apellido AS usuario_nombre, r.calificacion, r.comentario
    FROM C##eataway.Resenas r
    JOIN C##eataway.Usuarios u ON r.id_usuario = u.id_usuario
    WHERE r.id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Eventos Especiales por Local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerEventosEspecialesPorLocalSP(p_local_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_evento, nombre_evento, descripcion, fecha_evento, hora_evento
    FROM C##eataway.EventosEspeciales
    WHERE id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Promociones Activas
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerPromocionesActivasSP(p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_promocion, id_local, nombre, descripcion, fecha_inicio, fecha_fin
    FROM C##eataway.Promociones
    WHERE estado = 'Activa' AND fecha_fin >= SYSDATE;
END;


---------------------------------------------------

--Obtener locales por Categoria
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerLocalesPorNombreCategoriaSP(p_categoria_nombre VARCHAR2, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT l.id_local, l.nombre, l.descripcion, c.tipo AS tipo
    FROM C##eataway.Locales l
    JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria
    WHERE c.tipo = p_categoria_nombre;
END;

---------------------------------------------------

--Obtener Fotos de un Local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerFotosDeLocalSP(p_local_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_foto, ruta_foto
    FROM C##eataway.Fotos
    WHERE id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Número de Reservas por Local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerNumeroReservasPorLocalSP(p_local_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT COUNT(*) AS numero_reservas
    FROM C##eataway.Reservas
    WHERE id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Reseñas por Usuario
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerResenasPorUsuarioSP(p_usuario_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT r.id_resena, r.id_local, l.nombre AS local_nombre, r.calificacion, r.comentario
    FROM C##eataway.Resenas r
    JOIN C##eataway.Locales l ON r.id_local = l.id_local
    WHERE r.id_usuario = p_usuario_id;
END;

---------------------------------------------------

--Obtener Promociones por Local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerPromocionesPorLocalSP(p_local_id NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_promocion, nombre, descripcion, fecha_inicio, fecha_fin, estado
    FROM C##eataway.Promociones
    WHERE id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Ubicación y Contacto de los Locales
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerUbicacionYContactoPorLocalSP(
  p_local_id NUMBER, 
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT 
      l.id_local, 
      l.nombre AS local_nombre,
      u.provincia, 
      u.direccion,
      c.telefono,
      c.email,
      c.instagram
    FROM C##eataway.Locales l
    JOIN C##eataway.Ubicacion u ON l.id_local = u.id_local
    LEFT JOIN C##eataway.Contactos c ON l.id_local = c.id_local
    WHERE l.id_local = p_local_id;
END;

---------------------------------------------------

--Obtener Todas las Ubicaciones de un Local
CREATE OR REPLACE PROCEDURE C##eataway.ObtenerTodasUbicacionesPorLocalSP(
  p_local_id NUMBER, 
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT id_ubicacion, provincia, direccion
    FROM C##eataway.Ubicacion
    WHERE id_local = p_local_id;
END;

---------------------------------------------------
--VISTAS--
---------------------------------------------------

--Vista de Locales con Categoría y Foto
CREATE OR REPLACE VIEW C##eataway.V_LocalesConCategoriaYFoto AS
SELECT 
    l.id_local,
    l.nombre AS local_nombre,
    l.descripcion,
    c.tipo AS categoria,
    (SELECT f.ruta_foto FROM C##eataway.Fotos f WHERE f.id_local = l.id_local AND ROWNUM = 1) AS foto_principal
FROM C##eataway.Locales l
LEFT JOIN C##eataway.Categoria c ON l.id_categoria = c.id_categoria;

---------------------------------------------------

--Vista de Reservas con Información de Usuario y Local
CREATE OR REPLACE VIEW C##eataway.V_ReservasConUsuarioYLocal AS
SELECT 
    r.id_reserva,
    r.fecha,
    r.hora,
    r.numero_personas,
    r.descripcion AS reserva_descripcion,
    u.nombre || ' ' || u.primer_apellido AS usuario_nombre,
    l.nombre AS local_nombre
FROM C##eataway.Reservas r
JOIN C##eataway.Usuarios u ON r.id_usuario = u.id_usuario
JOIN C##eataway.Locales l ON r.id_local = l.id_local;

---------------------------------------------------

--Vista de Reseñas con Información de Usuario y Local
CREATE OR REPLACE VIEW C##eataway.V_ResenasConUsuarioYLocal AS
SELECT 
    r.id_resena,
    r.calificacion,
    r.comentario,
    u.nombre || ' ' || u.primer_apellido AS usuario_nombre,
    l.nombre AS local_nombre
FROM C##eataway.Resenas r
JOIN C##eataway.Usuarios u ON r.id_usuario = u.id_usuario
JOIN C##eataway.Locales l ON r.id_local = l.id_local;

---------------------------------------------------

--Vista de Eventos Especiales con Información de Local
CREATE OR REPLACE VIEW C##eataway.V_EventosEspecialesConLocal AS
SELECT 
    e.id_evento,
    e.nombre_evento,
    e.descripcion AS evento_descripcion,
    e.fecha_evento,
    e.hora_evento,
    l.nombre AS local_nombre
FROM C##eataway.EventosEspeciales e
JOIN C##eataway.Locales l ON e.id_local = l.id_local;

---------------------------------------------------

--Vista de Promociones Activas con Información de Local
CREATE OR REPLACE VIEW C##eataway.V_PromocionesActivasConLocal AS
SELECT 
    p.id_promocion,
    p.nombre AS promocion_nombre,
    p.descripcion AS promocion_descripcion,
    p.fecha_inicio,
    p.fecha_fin,
    l.nombre AS local_nombre
FROM C##eataway.Promociones p
JOIN C##eataway.Locales l ON p.id_local = l.id_local
WHERE p.estado = 'Activa';

